import { user02, user35, user42, user43 } from "../../utils/imagepath";

export const billersData = [
  {
    arch_id: "ARCH001",
    arch_name: "Rajesh Kumar Sharma",
    avatar: user42,
    arch_type: "Residential Architect",
    arch_category: "A",
    mobile: "+919876543210",
    mobileVerified: true,
    email: "rajesh.sharma@example.com",
    arch_address: "Plot No. 15, Sector 12, Dwarka, New Delhi, 110078",
    arch_city: "New Delhi",
    arch_state: "Delhi",
    status: "Active",
  },
  {
    arch_id: "ARCH002",
    arch_name: "Priya Joshi",
    avatar: user02,
    arch_type: "Commercial Architect",
    arch_category: "B",
    mobile: "+919123456789",
    mobileVerified: true,
    email: "priya.joshi@example.com",
    arch_address: "23/A, Koregaon Park, Pune, Maharashtra, 411001",
    arch_city: "Pune",
    arch_state: "Maharashtra",
    status: "Active",
  },
  {
    arch_id: "ARCH003",
    arch_name: "Arjun Patel",
    avatar: user43,
    arch_type: "Landscape Architect",
    arch_category: "C",
    mobile: "+919987654321",
    mobileVerified: false,
    email: "arjun.patel@example.com",
    arch_address: "12, Satellite Road, Ahmedabad, Gujarat, 380015",
    arch_city: "Ahmedabad",
    arch_state: "Gujarat",
    status: "Active",
  },
  {
    arch_id: "ARCH004",
    arch_name: "Meera Reddy",
    avatar: user35,
    arch_type: "Interior Architect",
    arch_category: "A",
    mobile: "+919876098760",
    mobileVerified: true,
    email: "meera.reddy@example.com",
    arch_address: "45, Jubilee Hills, Hyderabad, Telangana, 500033",
    arch_city: "Hyderabad",
    arch_state: "Telangana",
    status: "Inactive",
  },
  {
    arch_id: "ARCH005",
    arch_name: "Vikram Singh",
    avatar: user42,
    arch_type: "Urban Planner",
    arch_category: "B",
    mobile: "+919123098765",
    mobileVerified: true,
    email: "vikram.singh@example.com",
    arch_address: "78, Model Town, Ludhiana, Punjab, 141002",
    arch_city: "Ludhiana",
    arch_state: "Punjab",
    status: "Active",
  },
  {
    arch_id: "ARCH006",
    arch_name: "Kavya Nair",
    avatar: user02,
    arch_type: "Green Building Architect",
    arch_category: "D",
    mobile: "+919876012345",
    mobileVerified: false,
    email: "kavya.nair@example.com",
    arch_address: "56, Marine Drive, Kochi, Kerala, 682031",
    arch_city: "Kochi",
    arch_state: "Kerala",
    status: "Active",
  },
];